Resources:
  ssmparameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Type: String
      Value: param-value-dev
      Name: /param-key/environment
      Description: to create the parameter 
